[build]
builder = "dockerfile"

[deploy]
startCommand = "python main.py"

[environments]
[environments.production]
SUDO_USERS = "8225211569,8707693929"
BOT_TOKEN = "8729582864:AAEsEADH7wQXOlV5hm8bT1f_LhmLoN_INB0"
BOT_TOKEN2 = "8492531985:AAFfpR_e_hVglfNNi54xgCIFkr2fO50aNlk"
BOT_TOKEN3 = "8611361143:AAEfCrWbD_JODP3DNB9yLMBVN74nR0WZfyM"
BOT_TOKEN4 = "8749385192:AAHgpwpu6Hy9mIUa6k2fX4wQ6Qr38qLqW38"
BOT_TOKEN5 = "7979190403:AAFEu10OyXfdRi4ckTWjpfnRjmpXuMKZcts"
BOT_TOKEN6 = "8637265090:AAHDkPQ81u5ZBUtD-J2HHMoMoL53I-TZ_1I"
BOT_TOKEN7 = "8740366034:AAFF7sjnHH_R7LcBWS7e42dSBG07o9PwNng"
BOT_TOKEN8 = "8721234505:AAEA_BMNvqrWq07wTKxzoQ98LgEWEizn6-I"
BOT_TOKEN9 = "8715356761:AAFZ7RYkmt0B483xp6rsYTaEnNvIKHtbRGU"
BOT_TOKEN10 = "8514898003:AAFZyxjZOoI6lxIzzuV3glpvCLat8WknfNk"
MONGO_URI = "mongodb+srv://rj5706603:O95nvJYxapyDHfkw@cluster0.fzmckei.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"